## cartridge.properties for cartridge plugin_sfnext_page_designer
demandware.cartridges.plugin_sfnext_page_designer.multipleLanguageStorefront=true
demandware.cartridges.plugin_sfnext_page_designer.id=plugin_sfnext_page_designer
demandware.cartridges.plugin_sfnext_page_designer.version=1.1.0
