/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ============================================================================
// E2E Package ESLint Configuration
// ============================================================================
// Extends the root ESLint config with e2e-specific overrides
// This package uses TypeScript but does NOT use React
// ============================================================================

const baseConfig = await import('../eslint.config.js');

export default [
    ...baseConfig.default,
    {
        // E2E-specific ignores
        ignores: [
            '**/dist/**',
            '**/output/**',
            '**/steps.d.ts', // Auto-generated TypeScript definitions
            '**/*.cjs', // CommonJS config files (codecept.conf.cjs, etc.)
            '**/*.mjs', // ES module config files (eslint.config.mjs, .prettierrc.mjs)
            '**/node_modules/**',
            'eslint.config.mjs',
            '.prettierrc.mjs',
            'a11y-report/', // Generated by pnpm a11y:report (gitignored)
            'a11y-baseline.json', // Updated by pnpm a11y:update-baseline
        ],
    },
    {
        // Disable React-specific rules (this package doesn't use React)
        files: ['**/*.{ts,tsx,js,jsx}'],
        rules: {
            'react/react-in-jsx-scope': 'off',
            'react-hooks/rules-of-hooks': 'off',
            'react-hooks/exhaustive-deps': 'off',
            'react-refresh/only-export-components': 'off',
            'react/prop-types': 'off',
            'react/display-name': 'off',
        },
    },
    {
        // Allow comments in JSON files (e.g., tsconfig.json, package.json)
        files: ['**/*.json'],
        rules: {
            'jsonc/no-comments': 'off',
        },
    },
    {
        // Chai assertions use property chains (.to.be.true, .to.be.undefined, etc.)
        // which look like unused expressions to ESLint but are valid Chai assertions
        files: ['**/*.spec.ts'],
        rules: {
            '@typescript-eslint/no-unused-expressions': 'off',
        },
    },
    {
        // CodeceptJS recorder wraps all I.* methods to return thenables at runtime,
        // but their TypeScript definitions type them as void. This mismatch makes
        // the type-aware async rules unreliable — they fire or not depending on
        // type resolution (e.g. whether the generated steps.d.ts is present), which
        // causes local vs CI inconsistencies for these I.*-wrapping helpers.
        //   - await-thenable: fires on `await I.foo()` when I.foo is typed void.
        //   - require-await: fires on `async foo() { return I.grab() }` when the
        //     grab is typed non-thenable, so the promise passthrough looks
        //     await-less. steps.d.ts is gitignored and only emitted by `pnpm def`,
        //     so CI (which lints without it) resolves these differently than local.
        files: ['src/pages/**/*.ts', 'src/specs/**/*.ts', 'src/flows/**/*.ts', 'src/utils/**/*.ts'],
        rules: {
            '@typescript-eslint/await-thenable': 'off',
            '@typescript-eslint/require-await': 'off',
        },
    },
];
