/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** @sfdc-extension-file SFDC_EXT_PAGE_DESIGNER_TOOLKIT */
import {
    lazy,
    Suspense,
    useCallback,
    useId,
    useMemo,
    useRef,
    useState,
    type ComponentPropsWithoutRef,
    type CSSProperties,
} from 'react';
import { ArrowRight, PackageSearch, Plus, ShoppingBag } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { usePageDesignerMode } from '@salesforce/storefront-next-runtime/design/react/core';
import type { ComponentDesignMetadata } from '@salesforce/storefront-next-runtime/design/react';
import type { ShopperSearch } from '@/scapi';
import type { ComponentType } from '@/components/region';
import { DynamicImage } from '@/components/dynamic-image';
import ProductPrice from '@/components/product-price';
import { Button } from '@/components/ui/button';
import { Link } from '@/components/link';
import { useNavigate } from '@/hooks/use-navigate';
import { AttributeDefinition, Component, RegionDefinition } from '@/lib/decorators';
import { createProductUrl } from '@/lib/product/product-utils';
import { cn } from '@/lib/utils';
import type { Image } from '@/types';
import { normalizeShoppableImageConfig, type ShoppableImageConfig } from './model';
import type { ShoppableImageLoaderData } from './loaders';

// eslint-disable-next-line react-refresh/only-export-components
export { loader } from './loaders';
// eslint-disable-next-line react-refresh/only-export-components
export * from './model';

const CartItemModal = lazy(() =>
    import('@/components/cart-item-modal').then((module) => ({ default: module.CartItemModal }))
);
const ProductListDialog = lazy(() => import('./product-list-dialog'));

const HOTSPOT_THEMES = ['light', 'dark', 'brand'] as const;
type HotspotTheme = (typeof HOTSPOT_THEMES)[number];

/* v8 ignore start - decorators are covered through metadata assertions. */
@Component('shoppableImage', {
    name: 'Shoppable Image · Shop the Look',
    description:
        'Campaign image with interactive product hotspots, Quick Add, free product selection, or Product Set validation.',
    group: 'SFNextToolkit',
})
@RegionDefinition([])
export class SFNextToolkitShoppableImageMetadata {
    @AttributeDefinition({
        id: 'desktopImage',
        name: 'Desktop image',
        description: 'Select or upload the primary campaign image. It is displayed without automatic cropping.',
        type: 'image',
        required: true,
    })
    desktopImage?: Image;

    @AttributeDefinition({
        id: 'mobileImage',
        name: 'Mobile image (optional)',
        description: 'Optional mobile crop. When supplied, configure the mobile position of each hotspot as well.',
        type: 'image',
    })
    mobileImage?: Image;

    @AttributeDefinition({
        id: 'altText',
        name: 'Alternative text (required)',
        description:
            'Required before Apply is enabled. Describe the campaign scene without repeating the product list.',
        type: 'string',
        required: true,
    })
    altText?: string;

    @AttributeDefinition({
        id: 'hotspotConfig',
        name: 'Products and interactive hotspots',
        description:
            'Open the visual editor to choose free selection or Product Set mode, select products, and place desktop and mobile hotspots.',
        type: 'custom',
        required: true,
        editorDefinition: {
            type: 'SFNextToolkit.shoppableHotspots',
            configuration: {
                // Keep these as literals: Page Designer metadata is generated by static AST parsing.
                schemaVersion: 1,
                maxHotspots: 12,
            },
        },
    })
    hotspotConfig?: ShoppableImageConfig;

    @AttributeDefinition({
        id: 'showContentPanel',
        name: 'Show editorial panel',
        description: 'Displays an integrated title, description, and action panel below the image.',
        type: 'boolean',
        defaultValue: true,
    })
    showContentPanel?: boolean;

    @AttributeDefinition({
        id: 'heading',
        name: 'Heading',
        type: 'string',
        defaultValue: 'Shop the look',
    })
    heading?: string;

    @AttributeDefinition({
        id: 'description',
        name: 'Description',
        type: 'text',
    })
    description?: string;

    @AttributeDefinition({
        id: 'showViewAllButton',
        name: 'Show view-all button',
        description: 'Displays the action that opens the product list. Requires the editorial panel.',
        type: 'boolean',
        defaultValue: true,
    })
    showViewAllButton?: boolean;

    @AttributeDefinition({
        id: 'hotspotTheme',
        name: 'Hotspot style',
        type: 'enum',
        values: ['light', 'dark', 'brand'],
        defaultValue: 'light',
    })
    hotspotTheme?: string;

    @AttributeDefinition({
        id: 'showProductPreview',
        name: 'Show product preview on focus',
        description: 'On desktop, shows current name, price, and availability on hover or keyboard focus.',
        type: 'boolean',
        defaultValue: true,
    })
    showProductPreview?: boolean;

    @AttributeDefinition({
        id: 'showHotspotNumbers',
        name: 'Number hotspots',
        type: 'boolean',
        defaultValue: false,
    })
    showHotspotNumbers?: boolean;

    @AttributeDefinition({
        id: 'viewAllLabel',
        name: 'View-all label',
        type: 'string',
        defaultValue: 'View all products',
    })
    viewAllLabel?: string;

    @AttributeDefinition({
        id: 'shopSetLabel',
        name: 'Shop-set label',
        description: 'Opens the standard Quick Add for the Product Set.',
        type: 'string',
        defaultValue: 'Shop the set',
    })
    shopSetLabel?: string;

    @AttributeDefinition({
        id: 'viewSetLabel',
        name: 'View Product Set label',
        type: 'string',
        defaultValue: 'View set',
    })
    viewSetLabel?: string;
}
/* v8 ignore stop */

type ProductHit = ShopperSearch.schemas['ProductSearchHit'];

export interface ShoppableImageProps extends Omit<ComponentPropsWithoutRef<'section'>, 'children'> {
    desktopImage?: Image | string;
    mobileImage?: Image | string;
    altText?: string;
    hotspotConfig?: unknown;
    showContentPanel?: boolean;
    heading?: string;
    description?: string;
    showViewAllButton?: boolean;
    hotspotTheme?: string;
    showProductPreview?: boolean;
    showHotspotNumbers?: boolean;
    viewAllLabel?: string;
    shopSetLabel?: string;
    viewSetLabel?: string;
    regionId?: string;
    component?: ComponentType;
    componentData?: Record<string, Promise<unknown>>;
    designMetadata?: ComponentDesignMetadata;
    data?: ShoppableImageLoaderData | null;
}

type HotspotPositionStyle = CSSProperties & {
    '--hotspot-x-desktop': string;
    '--hotspot-y-desktop': string;
    '--hotspot-x-mobile': string;
    '--hotspot-y-mobile': string;
};

const resolveTheme = (value: string | undefined): HotspotTheme =>
    HOTSPOT_THEMES.includes(value as HotspotTheme) ? (value as HotspotTheme) : 'light';

const resolveImageUrl = (image: Image | string | undefined): string => {
    if (typeof image === 'string') return image.trim();
    return image?.url?.trim() || image?.path?.trim() || '';
};

const markerThemeClasses: Record<HotspotTheme, string> = {
    light: 'border-black/25 bg-white text-black shadow-lg hover:bg-white focus-visible:bg-white',
    dark: 'border-white/50 bg-black text-white shadow-lg hover:bg-black focus-visible:bg-black',
    brand: 'border-primary-foreground/50 bg-primary text-primary-foreground shadow-lg hover:bg-primary focus-visible:bg-primary',
};

const getProductImage = (product: ProductHit): string | undefined =>
    product.image?.disBaseLink ||
    product.image?.link ||
    product.imageGroups?.[0]?.images?.[0]?.disBaseLink ||
    product.imageGroups?.[0]?.images?.[0]?.link;

const isProductAvailable = (product: ProductHit): boolean => product.orderable !== false && product.inStock !== false;

function HotspotProductSummary({
    product,
    currency,
    tooltipId,
    x,
    y,
}: {
    product: ProductHit;
    currency?: string;
    tooltipId: string;
    x: number;
    y: number;
}) {
    const { t } = useTranslation('product');
    const image = getProductImage(product);
    const available = isProductAvailable(product);
    const horizontalPlacement = x <= 30 ? 'left' : x >= 70 ? 'right' : 'center';
    const verticalPlacement = y < 50 ? 'below' : 'above';

    return (
        <div
            id={tooltipId}
            role="tooltip"
            data-horizontal-placement={horizontalPlacement}
            data-vertical-placement={verticalPlacement}
            className={cn(
                'sfnext-shoppable-image__tooltip pointer-events-none absolute z-20 hidden w-56 max-w-[calc(100vw-2rem)] rounded-ui border border-border bg-popover p-3 text-popover-foreground opacity-0 shadow-xl transition-opacity motion-reduce:transition-none group-hover:opacity-100 group-focus-within:opacity-100 md:block',
                horizontalPlacement === 'left' && 'left-0',
                horizontalPlacement === 'center' && 'left-1/2 -translate-x-1/2',
                horizontalPlacement === 'right' && 'right-0',
                verticalPlacement === 'below' && 'top-[calc(100%+0.65rem)]',
                verticalPlacement === 'above' && 'bottom-[calc(100%+0.65rem)]'
            )}>
            <div className="flex gap-3">
                {image ? (
                    <DynamicImage
                        src={image}
                        alt=""
                        widths={[64]}
                        loading="lazy"
                        className="size-16 shrink-0 overflow-hidden rounded-sm [&_picture]:block"
                        imageProps={{ className: 'size-16 object-cover' }}
                    />
                ) : null}
                <div className="min-w-0 space-y-1 text-start">
                    <p className="line-clamp-2 text-sm font-semibold leading-tight">{product.productName}</p>
                    {currency ? (
                        <ProductPrice
                            product={product}
                            currency={currency}
                            hidePromo
                            className="text-sm"
                            currentPriceProps={{ className: 'text-sm font-semibold' }}
                        />
                    ) : null}
                    <p className={cn('text-xs font-medium', available ? 'text-success' : 'text-destructive')}>
                        {available ? t('inStock') : t('outOfStockLabel')}
                    </p>
                </div>
            </div>
        </div>
    );
}

function AuthoringNotice({ status }: { status: ShoppableImageLoaderData['status'] | 'missing-image' }) {
    const copy = {
        'missing-image': ['Select an image', 'Use the desktop image picker to begin.'],
        unconfigured: ['Configure hotspots', 'Open “Products and interactive hotspots” and add at least one product.'],
        'product-set-not-found': ['Product Set unavailable', 'Check its ID and assignment to the site catalog.'],
        'product-set-invalid': [
            'The product is not a Product Set',
            'Select a set product or switch to free selection mode.',
        ],
        'catalog-error': [
            'Catalog temporarily unavailable',
            'The image is published without hotspots until products can be loaded.',
        ],
        ready: ['', ''],
    } as const;
    const [title, description] = copy[status];

    return (
        <div
            role="status"
            data-status={status}
            className="flex min-h-64 w-full flex-col items-center justify-center gap-3 rounded-ui border border-dashed border-border bg-muted/40 p-8 text-center">
            <span className="flex size-12 items-center justify-center rounded-full bg-background text-muted-foreground shadow-sm">
                <PackageSearch className="size-6" aria-hidden="true" />
            </span>
            <div className="max-w-md space-y-1">
                <h3 className="text-lg font-semibold">{title}</h3>
                <p className="text-sm text-muted-foreground">{description}</p>
            </div>
        </div>
    );
}

export default function ShoppableImage({
    desktopImage,
    mobileImage,
    altText = '',
    hotspotConfig,
    showContentPanel = true,
    heading = 'Shop the look',
    description,
    showViewAllButton = true,
    hotspotTheme,
    showProductPreview = true,
    showHotspotNumbers = false,
    viewAllLabel = 'View all products',
    shopSetLabel = 'Shop the set',
    viewSetLabel = 'View set',
    className,
    regionId: _regionId,
    component: _component,
    componentData: _componentData,
    designMetadata: _designMetadata,
    data,
    ...props
}: ShoppableImageProps) {
    const { isDesignMode } = usePageDesignerMode();
    const { t } = useTranslation('product');
    const navigate = useNavigate();
    const titleId = useId();
    const [listOpen, setListOpen] = useState(false);
    const [listMounted, setListMounted] = useState(false);
    const [quickViewOpen, setQuickViewOpen] = useState(false);
    const [activeProductId, setActiveProductId] = useState<string | null>(null);
    const viewAllButtonRef = useRef<HTMLButtonElement>(null);
    const quickViewTriggerRef = useRef<HTMLElement | null>(null);
    const config = data?.config ?? normalizeShoppableImageConfig(hotspotConfig);
    const resolvedDesktopImage = resolveImageUrl(desktopImage);
    const resolvedMobileImage = resolveImageUrl(mobileImage);
    const theme = resolveTheme(hotspotTheme);
    const hotspots = data?.hotspots ?? [];
    const liveHotspots = isDesignMode ? hotspots : hotspots.filter(({ product }) => product);
    const uniqueProducts = useMemo(
        () => Array.from(new Map((data?.products ?? []).map((product) => [product.productId, product])).values()),
        [data?.products]
    );
    const productSetId = data?.productSetId;
    const showViewAllAction = showViewAllButton && uniqueProducts.length > 0;
    const showProductSetActions = config.sourceMode === 'productSet' && Boolean(productSetId);
    const showEditorialPanel =
        showContentPanel && Boolean(heading || description || showViewAllAction || showProductSetActions);

    const openQuickView = useCallback((productId: string, returnFocusTarget?: HTMLElement | null) => {
        setListOpen(false);
        quickViewTriggerRef.current = returnFocusTarget ?? null;
        setActiveProductId(productId);
        setQuickViewOpen(true);
    }, []);

    const handleQuickViewOpenChange = useCallback((open: boolean) => {
        setQuickViewOpen(open);
        if (open) return;

        const preferredTarget = quickViewTriggerRef.current;
        globalThis.setTimeout(() => {
            const target = preferredTarget?.isConnected ? preferredTarget : viewAllButtonRef.current;
            target?.focus();
        }, 0);
    }, []);

    const handleBuyNow = useCallback(() => {
        if (!activeProductId) return;
        setQuickViewOpen(false);
        void navigate(createProductUrl(activeProductId));
    }, [activeProductId, navigate]);

    const openProductList = useCallback(() => {
        setListMounted(true);
        setListOpen(true);
    }, []);

    if (!resolvedDesktopImage) {
        return isDesignMode ? <AuthoringNotice status="missing-image" /> : null;
    }

    const status = data?.status ?? 'unconfigured';
    const showAuthoringNotice = isDesignMode && status !== 'ready';

    return (
        <section
            {...props}
            data-slot="sfnext-toolkit-shoppable-image"
            data-source-mode={config.sourceMode}
            aria-labelledby={showEditorialPanel && heading ? titleId : undefined}
            className={cn('w-full min-w-0 space-y-5', className)}>
            <div
                data-slot="shoppable-image-surface"
                className="rounded-ui border border-border bg-card text-card-foreground shadow-ui">
                <div
                    className={cn(
                        'relative isolate z-10 bg-muted',
                        showEditorialPanel ? 'rounded-t-ui' : 'rounded-ui'
                    )}>
                    <DynamicImage
                        src={resolvedDesktopImage}
                        alt={altText}
                        widths={['100vw']}
                        loading="lazy"
                        className={cn('block w-full [&_picture]:block', resolvedMobileImage && 'hidden md:block')}
                        imageProps={{
                            className: cn('block h-auto w-full', showEditorialPanel ? 'rounded-t-ui' : 'rounded-ui'),
                        }}
                    />
                    {resolvedMobileImage ? (
                        <DynamicImage
                            src={resolvedMobileImage}
                            alt={altText}
                            widths={['100vw']}
                            loading="lazy"
                            className="block w-full md:hidden [&_picture]:block"
                            imageProps={{
                                className: cn(
                                    'block h-auto w-full',
                                    showEditorialPanel ? 'rounded-t-ui' : 'rounded-ui'
                                ),
                            }}
                        />
                    ) : null}

                    {liveHotspots.map((hotspot, index) => {
                        const tooltipId = `${titleId}-hotspot-${index + 1}`;
                        const product = hotspot.product;
                        const available = product ? isProductAvailable(product) : false;
                        const accessibleName = product
                            ? `${t('quickAdd')}: ${hotspot.label || product.productName}. ${available ? t('inStock') : t('outOfStockLabel')}`
                            : `Hotspot ${index + 1}: product ${hotspot.productId} unavailable`;
                        const positionStyle: HotspotPositionStyle = {
                            '--hotspot-x-desktop': `${hotspot.x}%`,
                            '--hotspot-y-desktop': `${hotspot.y}%`,
                            '--hotspot-x-mobile': `${hotspot.mobileX ?? hotspot.x}%`,
                            '--hotspot-y-mobile': `${hotspot.mobileY ?? hotspot.y}%`,
                        };

                        return (
                            <div
                                key={hotspot.id}
                                style={positionStyle}
                                className="sfnext-shoppable-image__hotspot group absolute left-[var(--hotspot-x-desktop)] top-[var(--hotspot-y-desktop)] z-10 -translate-x-1/2 -translate-y-1/2 hover:z-30 focus-within:z-30 max-[47.999rem]:left-[var(--hotspot-x-mobile,var(--hotspot-x-desktop))] max-[47.999rem]:top-[var(--hotspot-y-mobile,var(--hotspot-y-desktop))]">
                                <button
                                    type="button"
                                    aria-label={accessibleName}
                                    aria-describedby={product && showProductPreview ? tooltipId : undefined}
                                    aria-disabled={!product}
                                    disabled={!product}
                                    onClick={(event) =>
                                        product && openQuickView(product.productId, event.currentTarget)
                                    }
                                    className={cn(
                                        'sfnext-shoppable-image__marker flex size-11 items-center justify-center rounded-full border-2 text-sm font-bold transition-transform motion-reduce:transition-none motion-safe:hover:scale-110 motion-safe:focus-visible:scale-110 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring/70 disabled:cursor-not-allowed disabled:border-destructive disabled:bg-destructive/90 disabled:text-destructive-foreground',
                                        markerThemeClasses[theme]
                                    )}>
                                    {showHotspotNumbers ? index + 1 : <Plus className="size-5" aria-hidden="true" />}
                                </button>
                                {product && showProductPreview ? (
                                    <HotspotProductSummary
                                        product={product}
                                        currency={data?.currency}
                                        tooltipId={tooltipId}
                                        x={hotspot.x}
                                        y={hotspot.y}
                                    />
                                ) : null}
                            </div>
                        );
                    })}
                </div>

                {showEditorialPanel ? (
                    <div
                        data-slot="shoppable-image-editorial-panel"
                        className="grid gap-5 rounded-b-ui border-t border-border/70 bg-gradient-to-r from-card via-card to-muted/30 px-5 py-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center sm:px-7 sm:py-6">
                        <div className="max-w-2xl space-y-1.5">
                            {heading ? (
                                <h2 id={titleId} className="text-xl font-semibold tracking-tight sm:text-2xl">
                                    {heading}
                                </h2>
                            ) : null}
                            {description ? (
                                <p className="text-sm leading-6 text-muted-foreground">{description}</p>
                            ) : null}
                        </div>
                        <div className="flex flex-wrap gap-2 sm:justify-end">
                            {showViewAllAction ? (
                                <Button
                                    ref={viewAllButtonRef}
                                    type="button"
                                    className="w-full justify-between gap-3 sm:w-auto"
                                    onClick={openProductList}>
                                    {viewAllLabel}
                                    <ArrowRight className="size-4" aria-hidden="true" />
                                </Button>
                            ) : null}
                            {showProductSetActions && productSetId ? (
                                <>
                                    <Button
                                        type="button"
                                        variant={showViewAllAction ? 'outline' : 'default'}
                                        onClick={(event) => openQuickView(productSetId, event.currentTarget)}>
                                        <ShoppingBag className="size-4" aria-hidden="true" />
                                        {shopSetLabel}
                                    </Button>
                                    <Button asChild variant="ghost">
                                        <Link to={createProductUrl(productSetId)}>{viewSetLabel}</Link>
                                    </Button>
                                </>
                            ) : null}
                        </div>
                    </div>
                ) : null}
            </div>

            {showAuthoringNotice ? <AuthoringNotice status={status} /> : null}

            {listMounted ? (
                <Suspense fallback={null}>
                    <ProductListDialog
                        open={listOpen}
                        onOpenChange={setListOpen}
                        products={uniqueProducts}
                        currency={data?.currency}
                        title={heading || 'Products in this image'}
                        onQuickView={openQuickView}
                    />
                </Suspense>
            ) : null}

            {activeProductId ? (
                <Suspense fallback={null}>
                    <CartItemModal
                        productId={activeProductId}
                        open={quickViewOpen}
                        onOpenChange={handleQuickViewOpenChange}
                        onBuyNow={handleBuyNow}
                    />
                </Suspense>
            ) : null}
        </section>
    );
}

export function ShoppableImageFallback({
    desktopImage,
    mobileImage,
    altText = '',
    showContentPanel = true,
    heading = 'Shop the look',
    description,
}: Pick<
    ShoppableImageProps,
    'desktopImage' | 'mobileImage' | 'altText' | 'showContentPanel' | 'heading' | 'description'
> = {}) {
    const resolvedDesktopImage = resolveImageUrl(desktopImage);
    const resolvedMobileImage = resolveImageUrl(mobileImage);
    const showEditorialPanel = showContentPanel && Boolean(heading || description);

    if (!resolvedDesktopImage) {
        return (
            <div
                data-slot="sfnext-toolkit-shoppable-image-fallback"
                className="w-full animate-pulse space-y-4"
                aria-hidden="true">
                <div className="aspect-[4/5] w-full rounded-ui bg-muted sm:aspect-[16/9]" />
                {showContentPanel ? <div className="h-8 w-48 rounded bg-muted" /> : null}
            </div>
        );
    }

    return (
        <section
            data-slot="sfnext-toolkit-shoppable-image-fallback"
            className="w-full min-w-0 space-y-5"
            aria-busy="true">
            <div className="rounded-ui border border-border bg-card text-card-foreground shadow-ui">
                <div className={cn('relative isolate bg-muted', showEditorialPanel ? 'rounded-t-ui' : 'rounded-ui')}>
                    <DynamicImage
                        src={resolvedDesktopImage}
                        alt={altText}
                        widths={['100vw']}
                        loading="eager"
                        className={cn('block w-full [&_picture]:block', resolvedMobileImage && 'hidden md:block')}
                        imageProps={{
                            className: cn('block h-auto w-full', showEditorialPanel ? 'rounded-t-ui' : 'rounded-ui'),
                        }}
                    />
                    {resolvedMobileImage ? (
                        <DynamicImage
                            src={resolvedMobileImage}
                            alt={altText}
                            widths={['100vw']}
                            loading="eager"
                            className="block w-full md:hidden [&_picture]:block"
                            imageProps={{
                                className: cn(
                                    'block h-auto w-full',
                                    showEditorialPanel ? 'rounded-t-ui' : 'rounded-ui'
                                ),
                            }}
                        />
                    ) : null}
                    <span className="absolute left-1/2 top-1/2 size-11 -translate-x-1/2 -translate-y-1/2 animate-pulse rounded-full border-2 border-black/15 bg-white/80 shadow-lg" />
                </div>
                {showEditorialPanel ? (
                    <div
                        data-slot="shoppable-image-editorial-panel"
                        className="rounded-b-ui border-t border-border/70 bg-gradient-to-r from-card via-card to-muted/30 px-5 py-5 sm:px-7 sm:py-6">
                        <div className="max-w-2xl space-y-1.5">
                            {heading ? (
                                <h2 className="text-xl font-semibold tracking-tight sm:text-2xl">{heading}</h2>
                            ) : null}
                            {description ? (
                                <p className="text-sm leading-6 text-muted-foreground">{description}</p>
                            ) : null}
                        </div>
                    </div>
                ) : null}
            </div>
        </section>
    );
}

// eslint-disable-next-line react-refresh/only-export-components
export { ShoppableImageFallback as fallback };
