/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { registry } from '@/lib/page-designer/registry';

// STATIC_REGISTRY_START

/**
 * Initialize the static component registry.
 * This function is auto-generated by the staticRegistry Vite plugin.
 *
 * DO NOT EDIT THIS FUNCTION MANUALLY - it will be overwritten on next build.
 *
 * Components registered: Content.announcementBanner, Content.contentCard, Content.hero, Content.pdImage, Content.popularCategory, Content.productRecommendations, Content.productTile, Layout.grid, Layout.header, Layout.heroCarousel, Layout.popularCategories, Layout.productCarousel, Layout.productList, SFNextToolkit.accordion, SFNextToolkit.accordionItem, SFNextToolkit.blogPostGrid, SFNextToolkit.categoryCard, SFNextToolkit.categoryCarousel, SFNextToolkit.categoryHero, SFNextToolkit.contentCollection, SFNextToolkit.embeddedVideo, SFNextToolkit.heroBanner, SFNextToolkit.mediaContent, SFNextToolkit.productCard, SFNextToolkit.productCarousel, SFNextToolkit.productList, SFNextToolkit.productRecommendations, SFNextToolkit.promoCard, SFNextToolkit.promoGrid, SFNextToolkit.promoStrip, SFNextToolkit.responsiveColumns, SFNextToolkit.richText, SFNextToolkit.section, SFNextToolkit.trustBar, SFNextToolkit.trustItem
 */
export function initializeRegistry(targetRegistry = registry): void {
    targetRegistry.registerImporter(
        'Content.announcementBanner',
        () => import('../../components/announcement-banner/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter('Content.contentCard', () => import('../../components/content-card/index'));
    targetRegistry.registerImporter('Content.hero', () => import('../../components/hero/index'));
    targetRegistry.registerImporter('Content.pdImage', () => import('../../components/dynamic-image/index'));
    targetRegistry.registerImporter(
        'Content.popularCategory',
        () => import('../../components/home/popular-category/index'),
        { loader: 'loader' }
    );
    targetRegistry.registerImporter(
        'Content.productRecommendations',
        () => import('../../components/product-recommendations/index'),
        { loader: 'loader' }
    );
    targetRegistry.registerImporter('Content.productTile', () => import('../../components/product-tile/index'), {
        loader: 'loader',
    });
    targetRegistry.registerImporter('Layout.grid', () => import('../../components/grid/index'));
    targetRegistry.registerImporter('Layout.header', () => import('../../components/header/index'));
    targetRegistry.registerImporter('Layout.heroCarousel', () => import('../../components/hero-carousel/index'), {
        fallback: 'fallback',
    });
    targetRegistry.registerImporter(
        'Layout.popularCategories',
        () => import('../../components/home/popular-categories/index'),
        { loader: 'loader' }
    );
    targetRegistry.registerImporter('Layout.productCarousel', () => import('../../components/product-carousel/index'), {
        loader: 'loader',
        fallback: 'fallback',
    });
    targetRegistry.registerImporter('Layout.productList', () => import('../../components/product-list/index'));
    targetRegistry.registerImporter(
        'SFNextToolkit.accordion',
        () => import('../../components/sfnext-toolkit/accordion/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.accordionItem',
        () => import('../../components/sfnext-toolkit/accordion-item/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.blogPostGrid',
        () => import('../../components/sfnext-toolkit/blog-post-grid/index'),
        { loader: 'loader', fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.categoryCard',
        () => import('../../components/sfnext-toolkit/category-card/index'),
        { loader: 'loader', fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.categoryCarousel',
        () => import('../../components/sfnext-toolkit/category-carousel/index'),
        { loader: 'loader', fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.categoryHero',
        () => import('../../components/sfnext-toolkit/category-hero/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.contentCollection',
        () => import('../../components/sfnext-toolkit/content-collection/index'),
        { loader: 'loader', fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.embeddedVideo',
        () => import('../../components/sfnext-toolkit/embedded-video/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.heroBanner',
        () => import('../../components/sfnext-toolkit/hero-banner/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.mediaContent',
        () => import('../../components/sfnext-toolkit/media-content/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.productCard',
        () => import('../../components/sfnext-toolkit/product-card/index'),
        { loader: 'loader', fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.productCarousel',
        () => import('../../components/sfnext-toolkit/product-carousel/index'),
        { loader: 'loader', fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.productList',
        () => import('../../components/sfnext-toolkit/product-list/index')
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.productRecommendations',
        () => import('../../components/sfnext-toolkit/product-recommendations/index'),
        { loader: 'loader', fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.promoCard',
        () => import('../../components/sfnext-toolkit/promo-card/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.promoGrid',
        () => import('../../components/sfnext-toolkit/promo-grid/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.promoStrip',
        () => import('../../components/sfnext-toolkit/promo-strip/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.responsiveColumns',
        () => import('../../components/sfnext-toolkit/responsive-columns/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.richText',
        () => import('../../components/sfnext-toolkit/rich-text/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.section',
        () => import('../../components/sfnext-toolkit/section/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.trustBar',
        () => import('../../components/sfnext-toolkit/trust-bar/index'),
        { fallback: 'fallback' }
    );
    targetRegistry.registerImporter(
        'SFNextToolkit.trustItem',
        () => import('../../components/sfnext-toolkit/trust-item/index'),
        { fallback: 'fallback' }
    );
}

// STATIC_REGISTRY_END
